use_frameworks!

platform :ios, '10.0'

target 'LRCollectionColorFlowLayout_Example' do
  pod 'LRCollectionColorFlowLayout', :path => '../'

  target 'LRCollectionColorFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
